replicaCount: 1

fullImageName: "lemonpro/jokes-api:latest"
imagePullPolicy: Always
imagePullSecrets: []

containerPort: 8080

contextPath: "/jokes"

startupFailureThreshold: 10
livenessFailureThreshold: 10
readinessFailureThreshold: 10

resources:
  requests:
    memory: "750Mi"
    cpu: "500m"
  limits:
    memory: "1000Mi"
    cpu: "750m"
