replicaCount: 1

namespaceOverride: "jokes"
nameOverride: "random-jokes"
fullnameOverride: "random-jokes"

fullImageName: "lemonpro/jokes-api:latest"
imagePullPolicy: Always
imagePullSecrets: []

containerPort: 8080

contextPath: "/jokes"

startupFailureThreshold: 3
livenessFailureThreshold: 3
readinessFailureThreshold: 1

resources:
  requests:
    memory: "750Mi"
    cpu: "500m"
  limits:
    memory: "1000Mi"
    cpu: "750m"

envs:
  - name: JAVA_TOOL_OPTIONS
    value: "###ZARF_VAR_JAVA_TOOL_OPTIONS###"
