version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # security only
    commit-message:
      prefix: "chore(deps)"
