name: build

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Container Registry
        run: echo $DOCKER_HUB_TOKEN | docker login -u lemonpro --password-stdin
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Multi-stage docker build
        run: |
          docker build -t jokes-api:1.0.0-SNAPSHOT .

      - name: Tag & push to DockerHub Registry
        run: |
          docker tag jokes-api:1.0.0-SNAPSHOT index.docker.io/lemonpro/jokes-api:latest
          docker push index.docker.io/lemonpro/jokes-api:latest
